name: Notify chat about Dogi MC movement

on:
  schedule:
    - cron: '0 */2 * * *'

  workflow_dispatch:


permissions:
  contents: write
jobs:
  run_script:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script with secret
        run: python dogi_tracker.py "$CHAT_ID" "$API_KEY"

      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          git add dogi_data_v2.json
          git commit -m "Store dogi data"
          git push origin master
